### ISSUE TITLE
Question on updating packages

### ISSUE THREAD

**Issue by embano1** [jzelinskie/homebrew-go-get#1]
Hi,

Thx for taking this idea from Filippo further! 
Two questions on the script:

1. Would it make sense to install via `go get -u` flag to make sure go get pulls the most recent version (i.e. if already present in GOPATH)?
2. How would the general update of a package installed via brew go-get look like? Uninstall first, then reinstall or is it possible to somehow use `go get -u` instead?

**Comment by jzelinskie** [comment]
Sorry for never seeing this! My GitHub was configured to not watch new repositories, and this definitely wasn't 😢.

1. It's been a while since I took a look, but [this code](https://github.com/jzelinskie/homebrew-go-get/blob/9a947f3fba12d1275a2a27f34014621415a62e74/cmd/brew-go-get.rb#L28) makes it look we're passing anything you give `brew go-get` to `go get`, so all flags _can_ be used. GOPATHs are kept under the version of the software for which we're using [the current date](https://github.com/jzelinskie/homebrew-go-get/blob/9a947f3fba12d1275a2a27f34014621415a62e74/cmd/brew-go-get.rb#L24). This means that if it isn't the same day you ran the first `brew go-get`, it's going to give you a new GOPATH anyway, so -u isn't very useful.

2. Yeah, I was just uninstalling and reinstalling.

**Comment by embano1** [comment]
Thx
